# Generated by Django 5.1.4 on 2024-12-19 15:54

import Worker.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_certificate', models.ImageField(blank=True, null=True, upload_to=Worker.models.WorkerImagePath('certificate'))),
                ('worker_description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('GARDENER', 'Gardener'), ('ELECTRICIAN', 'Electrician'), ('PANITER', 'Painter')], default='GARDENER', max_length=25)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_charge', models.IntegerField()),
                ('service_image', models.ImageField(blank=True, null=True, upload_to=Worker.models.WorkerImagePath('serviceImages'))),
                ('approval_status', models.BooleanField(default=False)),
                ('available_status', models.BooleanField(default=False)),
                ('booked_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile')),
            ],
        ),
    ]
